services:
  db:
    image: postgres:16
    container_name: nest_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: test_db
    ports:
      - '5433:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
